#ifndef ENUMS_H
#define ENUMS_H

enum TOOL {PENCIL, ERASER, CIRCLE, TRIANGLE, RECTANGLE, POLYGON, SELECT};

enum COLOR {RED, ORANGE, YELLOW, GREEN, BLUE, INDIGO, VIOLET};

enum ACTION {NONE, UNDO, CLEAR, BRING_TO_FRONT, SEND_TO_BACK, RESIZE_UP, RESIZE_DOWN};

#endif
